### ISSUE TITLE
lua.js, lauxlib.js, lualib.js and luaconf.js should be only files required outside core modules

### ISSUE THREAD

**Issue by daurnimator** [fengari-lua/fengari#1]
- lua.js should export all functions from the core lua api (i.e. those that start with `lua_`) 
  - lauxlib.js should *only* require lua.js
  - l{baselib,corolib,mathlib}.js etc. should *only* require lua.js and lauxlib.js

**Comment by giann** [comment]
Agreed

**Comment by daurnimator** [comment]
We're almost there. Just need to figure out some of the llimits stuff.

**Comment by creationix** [comment]
How is this going?  I'm considering promoting fengari for some projects and having it better packaged will help adoption.

**Comment by giann** [comment]
What's left on that issue should not affect the end user.
You only need to `require('fengari')` to work with it.

**Comment by creationix** [comment]
What's the recommended way to use it in the browser?

**Comment by creationix** [comment]
Personally I'd like either vanilla script tags that work with `window.Fengari` and/or ES6 modules source that I can use rollup to build how I want.

**Comment by giann** [comment]
[web-cli-lua.js](https://github.com/fengari-lua/fengari-web-cli/blob/master/src/web-cli-lua.js) is how we do it for the REPL on [fengari.io](http://fengari.io/) currently.
But it's an ongoing discussion with @daurnimator who is thinking about implementing an asynchronous `require` that would fetch lua modules via xhr requests.

**Comment by giann** [comment]
Yes it is.
