### ISSUE TITLE
Show full stack trace on errors instead of just the error?

### ISSUE THREAD

**Issue by soccermitchy** [fengari-lua/fengari#124]
Whenever a Lua script has an error, it doesn't show the stack trace, only the error itself. This is making debugging code on, really, anything larger than a small project a pain to do. How would I go about getting a full stack trace?

**Comment by daurnimator** [comment]
I think this issue belongs in fengari-interop; could you refile over there?

FYI this is caused by fengari-interop not using a "message handler" when using `lua_pcall`.

**Comment by daurnimator** [comment]
There is an additional consideration: we don't know if errors were thrown intentionally: it seems odd that your error message suddenly get appended with a traceback.

**Comment by soccermitchy** [comment]
Just saw the original reply, I can move it when I get home to the other
repo.

**Comment by soccermitchy** [comment]
Crud, completely forgot about moving this. Do you still need me to or did you fix fengari-interop already to do that?

**Comment by daurnimator** [comment]
You can create the issue in fengari-interop if you want. I'm not convinced we *should* change the current behaviour though.

**Comment by daurnimator** [comment]
> Is it possible we can make it an optional feature? Not sure how we’d handle it, but it still may be useful.

Perhaps.
File the issue in the other repository and maybe we can get some 3rd opinions.
