### ISSUE TITLE
Include just base library

### ISSUE THREAD

**Issue by FizzerWL** [fengari-lua/fengari#130]
Hello!

In the fengari example, it calls `lualib.luaL_openlibs(L)` to load all built-in libraries.  This works fine, but I'd like to load libraries individually so I can tightly control what is available.

I figured out how to load most of them with code like this:

```
var loadLib = function (name, lib) {
	lauxlib.luaL_requiref(L, fengari.to_luastring(name), lib, 1);
	lua.lua_pop(L, 1); 
};
loadLib(lualib.LUA_STRLIBNAME, lualib.luaopen_string);
loadLib(lualib.LUA_COLIBNAME, lualib.luaopen_coroutine);
loadLib(lualib.LUA_TABLIBNAME, lualib.luaopen_table);
loadLib(lualib.LUA_MATHLIBNAME, lualib.luaopen_math);
loadLib(lualib.LUA_UTF8LIBNAME, lualib.luaopen_utf8);
```

However, I can't figure out how to load the luaopen_base.  It's not available in lualib, nor anywhere else that I can find.  How do I load the base libraries, so that I can use base functions like `pair`?

Thank you!

**Comment by daurnimator** [comment]
> I can't figure out how to load the luaopen_base. It's not available in lualib

Ah, that's an oversight. Happy to add it. Would be awesome if you could send a PR; otherwise I'll get to it later in the week.

> nor anywhere else that I can find

See linit.js:
```
const { luaopen_base } = require('./lbaselib.js');
```

Of course that export is private: it should be re-exported publically by lualib.
