### ISSUE TITLE
luaopen_base not exposed separately

### ISSUE THREAD

**Issue by fcrick** [fengari-lua/fengari#134]
I was trying to require a subset of the internal libraries, and I ended up with this, which works fine, but it seems like the extra import wasn't intentional, and could be exposed.

I'm using typescript - i'm not sure that affects this specific example or not, tbh.

```
import {lauxlib,lua,lualib,to_luastring,to_jsstring} from 'fengari'
import {luaopen_base} from 'fengari/src/lbaselib'

const defaultLibs = {
    _G: luaopen_base,
    math: lualib.luaopen_math,
    string: lualib.luaopen_string,
    table: lualib.luaopen_table,
}

function createState() {
    const L = lauxlib.luaL_newstate()
    for (const libName in defaultLibs) {
        lauxlib.luaL_requiref(L, to_luastring(libName), defaultLibs[libName], 1)
        lua.lua_pop(L, -1)
    }
    return L
}
```

The issue is needing to do `import {luaopen_base} from 'fengari/src/lbaselib'` separately. Seems like it should just be `lualib.luaopen_base` or something.

**Comment by daurnimator** [comment]
This has already been fixed on master (7a73809f38de36e01d1251c589523b13d0645582), it will be available in the next release.
