### ISSUE TITLE
__newindex with changed key leaves 'phantom nil' values in table

### ISSUE THREAD

**Issue by s-ol** [fengari-lua/fengari#138]
```lua
x = setmetatable({}, {
  __newindex = function(t,k,v)
    rawset(t,'_'..k,v)
  end
})
x.test = 4
for k,v in pairs(x) do
  print(k,v)
end
```
prints:

```
test	nil
_test	4
```

These 'phantom nils' stay in the table and come up on every invocation of `pairs`, breaking unrelated code. A quick fix mitigating this:
```lua
x = setmetatable({}, {
  __newindex = function(t,k,v)
    rawset(t, k, nil)
    rawset(t,'_'..k,v)
  end
})
```

**Comment by daurnimator** [comment]
Could you try out the fix in PR #139?

**Comment by s-ol** [comment]
@daurnimator sure, how can I build a single .js (like on the releases page) from the git tree?

**Comment by daurnimator** [comment]
> @daurnimator sure, how can I build a single .js (like on the releases page) from the git tree?

You mean of fengari-web? Should be just `npm run build` or `webpack -p`. See the README: https://github.com/fengari-lua/fengari-web#building

**Comment by daurnimator** [comment]
huh. I too now get that error. Sent https://github.com/fengari-lua/fengari-web/pull/33 to fix (via updating to renamed babel packages)
