### ISSUE TITLE
Improve default loader performance

### ISSUE THREAD

**Issue by s-ol** [fengari-lua/fengari#140]
As chrome points out, *synchroneus XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.*.

Besides just using a deprecated API, this has other negative side effects: for example I would like to use

    <link rel="preload" as="fetch" href="/lib/mmmfs/browser.lua" />

to preload requests, as the synchronous and often long chains of sequential module fetches take much longer than necessary. However, while chrome will preload these, it will *not* use them and complains with the following message:

     A preload for 'https://mmm.s-ol.nu/lib/mmmfs/browser.lua' is found, but is not used because the new request is synchronous.

Maybe it would be possible to use an asynchronous fetch method on the JS side and simply halt all Lua execution until the request completes? This sounds to me like it would be compatible behaviour, but would get rid of these drawbacks.

Additionally, an async require version could or should be required to let fengari users write more performant software.

**Comment by s-ol** [comment]
Also I see two full HTTP transactions for each successful require - with my 5+ seconds of page load time at the moment I would *really* like to just cut that in half.

**Comment by daurnimator** [comment]
> A preload for 'https://mmm.s-ol.nu/lib/mmmfs/browser.lua' is found, but is not used because the new request is synchronous.

Ouch. I didn't know that chrome did such a thing: seems like a terrible idea on their part!

 > Maybe it would be possible to use an asynchronous fetch method on the JS side and simply halt all Lua execution until the request completes?

Sadly this is not possible. To get proper `require` semantics we *must* use a sync request.

----

The best way to use fengari is to preload everything you need into your lua state, that way a sync request is never done. We created [fengari-loader](https://github.com/fengari-lua/fengari-loader/) to help people with that sort of thing.

**Comment by s-ol** [comment]
> Sadly this is not possible. To get proper require semantics we must use a sync request.

That's why I mentioned halting/suspending all Lua execution until the request completes - I understand require must stay synchronous, at least as seen from the Lua side. It's however definitely a bad practice to stall the whole browser for the full duration of a network fetch, for whatever reason, and disruptive especially when Lua and JS code are used at the same time but not interacting
