### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by dkrikun** [fengari-lua/fengari#143]
Hello,

Why would one want to use fengari over vvanders/wasm_lua or paulcuth/starlight?
Asking to understand the technology

**Comment by giann** [comment]
Startlight is a transpiler, thus you can't use coroutine with it.
WASM doesn't let you interact with the DOM right now and maybe never will. Plus it will lead to memory issues because of the two competing garbage collectors. Fengari lets JS manage memory.

**Comment by dkrikun** [comment]
Thank you for the explanation.
Regarding memory, isn't it feasible to emulate malloc() as used in lua by means of js garbage collector?
Regarding wasm, if I understand correctly there is no inherent limitation of wasm per se here..

**Comment by giann** [comment]
No but you would have to rewrite Lua without GC in wasm. Which would be a daunting task without real benefits to it.

You don’t have any control over JS GC in the browser.
