### ISSUE TITLE
Babel plugin?

### ISSUE THREAD

**Issue by darrenjennings** [fengari-lua/fengari#145]
Instead of loading the entire fegari/interop library, it would be nice instead to have a babel plugin that can "transpile" to javascript.

e.g.

```lua
local a = "hello world"
print(a)
```

would output:

```js
const a = "hello world"
console.log(a)
```

**Comment by daurnimator** [comment]
Fengari is not a transpiler, it is a VM. Perhaps see my presentation from the 2017 lua workshop: https://www.lua.org/wshop17.html#Daurnimator1
