### ISSUE TITLE
Why all the strings are "long"?

### ISSUE THREAD

**Issue by Egor-Skriptunoff** [fengari-lua/fengari#150]
When dumping a short string constant (like `"abc"`):
 - Fengari sets `LUA_TLNGSTR` as the constant type
 - PUC Lua sets `LUA_TSHRSTR` as the constant type

As a result, the `string.dump()` returns different bytecodes in Fengari and in PUC Lua.
Of course, it's not a bug: a Fengari bytecode can be loaded in PUC Lua and vice versa.
But this situation looks suspicious assuming that
_"the intention of fengari is to follow Lua as close as possible"_ (c)

How `LUAI_MAXSHORTLEN` is defined in Fengari?
In PUC Lua it can't be smaller than 10 (https://www.lua.org/source/5.3/llimits.h.html#LUAI_MAXSHORTLEN answers the question "why?").
So, every string of length below 10 in PUC Lua is always of type `LUA_TSHRSTR`.

If for some reason short strings are not implemented at all in Fengari,
it may be a good(?) idea to emulate PUC Lua behavior of `string.dump`:
to replace real type with `LUA_TSHRSTR` when dumping strings of length up to 40.

We were promised _bug-for-bug compatibility with Lua 5.3_ after all  :-)

**Comment by daurnimator** [comment]
The main difference between short strings and long strings in Lua is that short strings are [interned](https://www.lua.org/source/5.3/lstring.c.html#internshrstr). i.e. there is an internal table from `string contents` -> `string pointer`.
I skipped doing this in fengari, as the interned string table wouldn't be handled correctly by the javascript garbage collector.

I'm tempted to say that in fengari, `LUAI_MAXSHORTLEN` is `-1`; the >= 10 limitation doesn't apply to us.

Bytecode... oddities (**not** incompatibilities) are no a stranger to us. e.g. [The number type](https://github.com/fengari-lua/fengari#integers`) is one place where you'll have a hard time finding a lua installation that emits the same as fengari.

**Comment by Egor-Skriptunoff** [comment]
Yes, this difference in bytecodes probably doesn't lead to an incompatibility, so fixing is not necessary.
