### ISSUE TITLE
String Lib repeat implementation is slightly incorrect

### ISSUE THREAD

**Issue by KevBruner** [fengari-lua/fengari#154]
string.rep should "Returns the empty string if n is not positive." (from the Lua documentation). The Fengari implementation errors with "resulting string too large" if you pass -1 to string.rep. 

The following code works under standard Lua but fails in Fengari
```
local var = "hello"
var = string.rep( "hello", -1 )

```

**Comment by daurnimator** [comment]
Seems to work for me:

```lua
a=string.rep("hello", -1);
print(type(a), #a) -- output: string	0
```

**Comment by KevBruner** [comment]
Sorry, I wasn't on the latest code. This does seem to have been addressed in the head revision.

**Comment by daurnimator** [comment]
Which code were you on? I think the code has been the same for all releases so far.
