### ISSUE TITLE
Creating callbacks with global functions

### ISSUE THREAD

**Issue by grilme99** [fengari-lua/fengari#161]
How can I execute a Lua callback from JavaScript? Heres an example code snippet.

```Lua
while true do
    test(function()
        print('Hello world')
    end)
end
```

And here is my JavaScript code
```JavaScript
test: (callback) => {
      testt().then(() => {
        lua_resume(L, null, 0)
        // Execute callback
      })
      return lua_yield(L, 0)
    },
```

I want to execute the callback after two seconds. I've already got waiting working, I just don't know how to do callbacks.

**Comment by grilme99** [comment]
Any help with this?

**Comment by lorenzos** [comment]
Why not just waiting for `test()` in a coroutine?

```lua
coroutine.wrap(function() 

    while true do
        test()
        print('Hello world')
    end

end)()
```

**Comment by grilme99** [comment]
Anyone will be able to execute code with what I am making. I feel like callbacks would be the best way. I need to be able to pass arguments to the callback as well.

**Comment by lorenzos** [comment]
> I need to be able to pass arguments to the callback as well.

You can make test return those arguments pushing them onto the stack befare calling `lua_resume`:

```lua
coroutine.wrap(function() 
    while true do
        args = test()
        print(args)
    end
end)()
```

Also, I want to point out that your example is not a callback (in JS common terminology): `test()` yields until its "callback" function is called, so the execution of the Lua script doesn't continue.

Anyway, I don't know how you could read a parameter of type `LUA_TFUNCTION` from the stack and call that Lua function later from Javascript, I don't see an obvious API for that...

Maybe you could try this way using (fengari-interop)[https://github.com/fengari-lua/fengari-interop]'s [`tojs`](https://github.com/fengari-lua/fengari-interop#tojsl-idx) (not tested, just an idea):

```js
    test: () => {
      testt().then(() => {
        var callback = fengari.interop.tojs(L, 1);
        lua_resume(L, null, 0)
        fengari.interop.invoke(/*this, [args...]*/);
      })
      return lua_yield(L, 0)
    },
```

From `tojs()` doc:

**Comment by daurnimator** [comment]
You should only call `lua_resume` from a "lua JS function" or top level. Not from a fengari-interop function.

Create your test function via `fengari.lua.lua_pushjsfunction` instead (and follow the Lua C API contract).

**Comment by lorenzos** [comment]
> Not from a fengari-interop function.

How did you assumed he did that?

**Comment by daurnimator** [comment]
> How did you assumed he did that?



> ```js
> test: (callback) => {
> ```

**Comment by grilme99** [comment]
Hi, sorry for the late reply, I've been on holiday.

@lorenzos I can't seem to be able to use Interop tojs because I don't have to JS library loaded into state because of sandboxing.

**Comment by lorenzos** [comment]
@grilme99 You don't need interop from Lua state, my code suggestion is JS, not Lua.

**Comment by grilme99** [comment]
Yes, but for it to work, the JS library must be loaded into state. I don’t load it due to sand boxing.

**Comment by daurnimator** [comment]
@grilme99 you write the function in JS without fengari-interop. Push it into fengari with `lua_pushjsfunction`.
