### ISSUE TITLE
Does step-by-step debugging work?

### ISSUE THREAD

**Issue by d9k** [fengari-lua/fengari#170]
Hello! I really wish to use fengari but doubts in it's debugging capabilites hold me from it.

Previosly I posted the request 
https://github.com/fengari-lua/fengari-devtools/issues/2

Is step-by-step debugging and setting breakpoints by click are available now?
What are implementation difficulties?

**Comment by daurnimator** [comment]
> Is step-by-step debugging and setting breakpoints b

Step by step debugging has always been able to work the same in fengari as in normal lua (i.e. with `debug.sethook`/`lua_sethook`).

> by click

No; only fengari-devtools has any sense of "click"

**Comment by daurnimator** [comment]
Closing as there is nothing actionable here
