### ISSUE TITLE
Table length

### ISSUE THREAD

**Issue by dooleydiligent** [fengari-lua/fengari#173]
Sorry for the noob question, but how do I find the table length?
From here https://www.lua.org/pil/27.1.html I expect to find an implementation of luaL_getn but don't.

I see luaH_getn but can't find any clear way to use it except to 
require('fengari/src/ltable') 
but that seems wrong.

Thanks.

**Comment by daurnimator** [comment]
- `luaL_getn` was renamed to `lua_objlen` in 2006
  - `lua_objlen` was renamed to `lua_rawlen` in 2011

You may want [`luaL_len`](https://www.lua.org/manual/5.3/manual.html#luaL_len) instead.

You really should use a newer reference than the online PiL (which was written in 2003)
