### ISSUE TITLE
_, _, cap1 = '-':find('-') cap1  should return nil instead of empty string

### ISSUE THREAD

**Issue by XuHaoJun** [fengari-lua/fengari#185]
``` lua
foo = "-"
_, _, cap1 = foo:find(foo)
print(cap1 == "")
print(cap1 == nil)
if cap1 then
  print("should never reach here!")
end
```
different result in fengari between native lua.
in my usecase is `-1 Dexterity per 1 Dexterity on Allocated Passives in Radius`

**Comment by mxdpeep** [comment]
this repo is dead

**Comment by daurnimator** [comment]
> this repo is dead

nope. no one has submitted a PR to fix this.

Bugs and/or changes to the code in this repo is rare, as Lua 5.3 is a fixed target.

**Comment by daurnimator** [comment]
Bugfix in https://github.com/fengari-lua/fengari/pull/195
