### ISSUE TITLE
How to define global objects?

### ISSUE THREAD

**Issue by evantahler** [fengari-lua/fengari#187]
I'm using this awesome library as a part of https://github.com/stipsan/ioredis-mock, which lets us mock the Redis server, complete with LUA scripting!

The Redis implementation of LUA has some global extensions loaded in, most importantly for me `cjson`.  For testing, I'm totally happy to stub these their JS versions `JSON.encode/decode`, but I can't quite sort out how to make a global object to match `cjson.encode/decode`.

Making Global Functions:
```
  lua.lua_pushjsfunction(L, fn);
  lua.lua_setglobal(L, toLuaString(name));
```

... but what about objects?

**Comment by daurnimator** [comment]
> ... but what about objects?

Use `lua_createtable` and `lua_pushjsfunction` and `lua_setfield`. Or use `luaL_newlib` which is a wrapper around this for you.
