### ISSUE TITLE
Add support for 64 Bit Integers

### ISSUE THREAD

**Issue by MetaIdea** [fengari-lua/fengari#197]
To properly handle cryptography etc. we definitely need 64 bit integer support. Also please consider the [year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem).

Thank you for the hard work so far !

**Comment by daurnimator** [comment]
Fengari is limited by what Javascript supports; and Javascript doesn't support 64 bit integers.

Related: https://github.com/fengari-lua/fengari/issues/128
