### ISSUE TITLE
Calling keyword functions (then,end,etc)

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [fengari-lua/fengari#200]
As it stands, a lot of js results in objects having :then or :end function calls, and lua doesn't handle this well. They can be called very easily, via ["end"] and similar, but this results in situations where I have to call `obj["end"](obj)`, where obj:end() is much cleaner. 
Is there a way these can somehow be mapped to _end/_then or something along those lines? Am I just using everything wrong?

**Comment by giann** [comment]
There's no way around it, you have to use the `["end"]` notation. We won't add new semantics to Lua.
