### ISSUE TITLE
Feature Request: support CJSON

### ISSUE THREAD

**Issue by shayff** [fengari-lua/fengari#207]
CJSON is popular library in Lua, will be great to have a support for this.

**Comment by daurnimator** [comment]
fengari doesn't "support" libraries: it's up to those libraries to support fengari.

Note that CJSON is written in C.... it's right there in the name; so there is no real path to use it with fengari.
However you likely already have a json parser from your javascript runtime. e.g. `js.global.JSON.parse`.
