### ISSUE TITLE
JS api isn't working as expected.

### ISSUE THREAD

**Issue by DoubleShotgun** [fengari-lua/fengari#212]
```HTML
<script src="fengari-web.js" type="text/javascript"></script>
<script type="text/javascript">
      const luaconf  = fengari.luaconf;
      const lualib   = fengari.lualib;
      const lua      = fengari.lua;
      const lauxlib  = fengari.lauxlib;

      const L = lauxlib.luaL_newstate();

      lauxlib.luaL_dostring(L, "a=7+11");
      lua.lua_getglobal(L, "a");
      console.log(lua.lua_tonumber(L,-1));
</script>
```
Because that the JS api is the same as C api, I'm expecting it to output:

`18`

But I got:

`0`

Is there something I'm doing wrong, or is it fengari?

**Comment by daurnimator** [comment]
> Is there something I'm doing wrong

It works if you pass a fengari string to `luaL_dostring` rather than a normal javascript string:
`lauxlib.luaL_dostring(L, fengari.to_luastring("a=7+11"));`
This was (badly) reported via the `-1` returned by your `luaL_dostring` call.
