### ISSUE TITLE
Getting fetch response in lua

### ISSUE THREAD

**Issue by DoubleShotgun** [fengari-lua/fengari#213]
I want to do this:
```js
fetch(url)
.then(response => response.json()).then(json => {
  console.log(json)
})
```
But in lua.

I tried this:
```lua
local promise = window:fetch(url)

promise["then"](promise, function() --[[get response?]] end)
```
But I have no idea how to get the response.

**Comment by giann** [comment]
You can wrap the call in a coroutine and yield the result from within the callback.

**Comment by giann** [comment]
Just add the argument to the callback function.

**Comment by DoubleShotgun** [comment]
Like this?
`promise["then"](promise, function(response) print(response) end)` if so, it is just given me a nil.

Btw the link I'm using does work.

**Comment by giann** [comment]
Yes the first argument is `this` which is null in this context. Add a second one
