### ISSUE TITLE
tostring number cause issue due a trail ".0"

### ISSUE THREAD

**Issue by shaypep** [fengari-lua/fengari#214]
Hey guys,
I have encountered an issue with my Lua code. In the code, I am creating a string that represents a number using the following approach:

```
local futureDate = 5000000000
local now = redis.call("TIME")
local currentScore = '0.'..(futureDate-tonumber(now[1]))
```

The expected result should be something like "0.23412351321".

The code work fine in production, however, when I run this code using fengari, I notice that the resulting string includes an additional ".0". 
As a consequence, when I attempt to convert this string back into a number using a Lua operation, it fails and returns "NaN".

I debug and found out the issue related to that code:
https://github.com/fengari-lua/fengari/blame/eb2453c0c36f3802c8effeb65f36090de0c59a0e/src/lobject.js#L593

Could you please provide any insights or suggestions on how to resolve this issue?
Thank you in advance for your assistance.

**Comment by RyanSquared** [comment]
```lua
local futureDate = 5000000000
local now = redis.call("TIME")
local currentScore = '0.'..(futureDate-tonumber(math.tointeger(now[1])))
```

note that in 5.3, the behavior of how numbers changed, and floats and integers are serialized differently despite being the same approximate "number" type:

```
ryan@de2 ~ 14:05:11 % lua5.3
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> tostring(5 + 0.0)
5.0
> tostring(math.tointeger(5 + 0.0))
5
```

**Comment by giann** [comment]
Because all numbers in JS are f64 and we can't represent 64bits integers with them so effectively fengari is Lua 5.3 semantics with the `LUA_INT_TYPE=LUA_INT_LONG` option

**Comment by daurnimator** [comment]
> Could you please provide any insights or suggestions on how to resolve this issue?

Instead of concatenating `0.` on yourself, do a division, e.g. `0.5 - redis.call("TIME") / 10000000000.0`
