### ISSUE TITLE
tostring of infinity doesn't match PUC

### ISSUE THREAD

**Issue by technomancy** [fengari-lua/fengari#217]
It's a very small thing but in the reference implementation of Lua (as well as LuaJIT), infinity prints as `inf`, whereas in Fengari it prints as `Infinity`.

Seems it would be nice if it was the same.

**Comment by daurnimator** [comment]
IIRC lua prints infinity differently based on which system you run it on. e.g. on linux it might print `inf`, on windows `Infinity` and something else on more esoteric systems.

**Comment by technomancy** [comment]
Aha; I had no idea this was unspecified. Good to know!

**Comment by daurnimator** [comment]
> Aha; I had no idea this was unspecified. Good to know!

lua itself relies on libc to implement the conversion using `sprintf(buf, "%.14g", x)`
https://www.lua.org/source/5.3/luaconf.h.html#lua_number2str

On your system that may be `inf`, but e.g. using Microsoft Visual Studio 2010 you might get `1.#INF00` (see https://stackoverflow.com/questions/6235847/how-to-generate-nan-infinity-and-infinity-in-ansi-c#comment7267271_6235876 )! 

fengari uses https://github.com/fengari-lua/fengari/blob/eb2453c0c36f3802c8effeb65f36090de0c59a0e/src/luaconf.js#L153-L155
