### ISSUE TITLE
"getting started" section in readme

### ISSUE THREAD

**Issue by TehShrike** [fengari-lua/fengari#68]
I'd love to try this in a web project - could the readme/fengari.io be given a section with instructions on how to install Fengari and use it in a project?

**Comment by giann** [comment]
A more elaborate README is indeed needed and is coming.
In the meantime you can take a look at how we wrote the web [REPL](https://github.com/fengari-lua/fengari-web-cli/).

**Comment by creationix** [comment]
Even if we can just get a simple "Include these script tags in your head and then you can write Lua<->JS api bindings" would be a great start.  For anyone who knows the lua C api and JS, that should be enough to get started.

Then others could write more detailed examples of how to write JS bindings and give some full examples.

**Comment by daurnimator** [comment]
We've updated the README here now.
Most people (i.e. those that want to use fengari in the browser) should be looking at fengari-web: https://github.com/fengari-lua/fengari-web#getting-started

**Comment by creationix** [comment]
@daurnimator awesome.  How hard is it to add bindings to the fengari-web?  Just fork the code, edit, and rebuild the dist bundle? 

I don't mean bindings intended to be merged upstream, just custom bindings for my app.

**Comment by giann** [comment]
Not sure i get your question ?

**Comment by creationix** [comment]
Actually, I can probably just do it in another script tag, assuming the fengari-web bundle exposes the binding API functions via `window` somehow.

**Comment by giann** [comment]
fengari-web doesn't expose anything to the js side. Its job is to run lua script tags. But you can load fengari itself and have access to the API from `window`. See [here](https://github.com/fengari-lua/fengari#the-js-api) to see how the API is structured.

**Comment by creationix** [comment]
I don't want to include two copies of fengari.  I guess I could tweak fengari-web to expose the `fengari` object as `window.fengari` before building?

**Comment by giann** [comment]
Yes you could do that. You can also don’t use fengari-web at all and run your main lua script with the API. You can then load any other lua module by requiring them in said main script.

**Comment by creationix** [comment]
I see, I thought there was more to fengari-web like dom bindings.  It appears to be just a quick runner to run script tags.

**Comment by giann** [comment]
Theres’s no web specific bindings. And i don’t know which one you would need. Fengari-interop let you use any web api directly whithout effort.

**Comment by daurnimator** [comment]
> I thought there was more to fengari-web like dom bindings.

Talking between fengari and JS (and hence the DOM) is usually done via https://github.com/fengari-lua/fengari-interop

**Comment by daurnimator** [comment]
Though I did just realise that we have an issue around [how JS modules are loaded](https://github.com/fengari-lua/fengari/blob/9d6c4a49e0b6c845bc3fdeb4959377ca42e56832/src/loadlib.js#L45): loaded modules need access to the 'fengari' library.

**Comment by daurnimator** [comment]
Though I did just realise that we have an issue around [how JS modules are loaded](https://github.com/fengari-lua/fengari/blob/9d6c4a49e0b6c845bc3fdeb4959377ca42e56832/src/loadlib.js#L45): loaded modules need access to the 'fengari' library.
