### ISSUE TITLE
[doc] Be more clear about which version(s) of Lua is/are targeted

### ISSUE THREAD

**Issue by raingloom** [fengari-lua/fengari#70]
I couldn't really figure it out from the readme, which imo I should be able to do. I wanna know where I'll be able to yield and if I can use _ENV and that kind of stuff.

**Comment by RyanSquared** [comment]
I would assume 5.3 given there's a link to *only* the 5.3 source, no other versions.

**Comment by daurnimator** [comment]
@raingloom Thanks, will do :)

**Comment by daurnimator** [comment]
Better with https://github.com/fengari-lua/fengari/blob/99223779c613f7c612d69bb9184164d8270b1a74/README.md#semantics ?

**Comment by raingloom** [comment]
Yes, thanks for the fix!
