### ISSUE TITLE
Investigate WeakMap to implement weak tables with __mode="k"

### ISSUE THREAD

**Issue by giann** [fengari-lua/fengari#72]

**Comment by daurnimator** [comment]
I think the issue I ran into last time I looked at this was that lua weak tables are iterable; while JS weakmaps are not.

**Comment by daurnimator** [comment]
Yeah I don't think this is possible due to requirements around `next`.

**Comment by s-ol** [comment]
@daurnimator @giann  I think this should now be possible with individual [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#browser_compatibility)s wrapped in a datastructure that takes care of the iteration.
