### ISSUE TITLE
Some test cases fail on Windows

### ISSUE THREAD

**Issue by dlbd** [fengari-lua/fengari#83]
```
⨯ math.exp
  not ok 271 Correct element(s) on the stack
    ---
      operator: equal
      expected: 22026.465794806718
      actual:   22026.46579480671
```

What is the correct way to compare floating point numbers with the ``tape`` framework? Just ``abs(a - b) < e``, or is there a helper function? Other tests involving floating point numbers (``math.log``, ``math.cos``, etc) are not failing, but perhaps they should be changed as well...

```
⨯ os.getenv
  not ok 337 Correct element(s) on the stack
    ---
      operator: ok
      expected: true
      actual:   false
```

There's no ``HOME`` env variable, so the test fails. ``PATH`` could be used instead.

**Comment by daurnimator** [comment]
> What is the correct way to compare floating point numbers with the tape framework?

This is meant to be exact. This looks like a bug in node.

> There's no HOME env variable, so the test fails. PATH could be used instead.

Happy to make that change => send a PR if you'd like, I can probably do it tomorrow.

**Comment by dlbd** [comment]
> This is meant to be exact. This looks like a bug in node.
Could be, upgrading node from 6.11.3 to 8.4.0 fixed this.
> Happy to make that change => send a PR if you'd like, or I can probably do it tomorrow.
You can make that change.
I've noticed that ``HOME`` is set when the tests are run from ``npm test``, but not if I do ``tape tests/*.js tests/test-suite/*.js`` manually. ``PATH`` is always present.

**Comment by daurnimator** [comment]
Okay to close this issue?

**Comment by dlbd** [comment]
Yes, thanks.
