### ISSUE TITLE
Simple start 

### ISSUE THREAD

**Issue by egordorichev** [fengari-lua/fengari#84]
Hello!
Amazing project, but I can't see any `Getting Stating` docs. How do I setup it for plain JS (no node.js)? 
I saw web REPL, but it doesn't explain, where to get some files, and it also uses `require`. Thanks!

**Comment by rokf** [comment]
There is an issue with the same topic open at #68 :smile:.

**Comment by daurnimator** [comment]
Closing as duplicate of #68
