### ISSUE TITLE
How to execute a returned lua function (example: currying?)

### ISSUE THREAD

**Issue by cristiano-belloni** [fengari-lua/fengari#87]
Hi all,
I'm a JS developer and I'm learning the first steps with lua and fengari.

A (I hope) simple question: would it be possible to store and execute later a function returned by a lua function? I'm experimenting with simple currying while embedding lua, just to get a sense of how it works and I'm at this point (see the TODO statements):

``` javascript
global.WEB = false
const fengari = require('./fengari/src/fengari')
const lua = fengari.lua
const lauxlib = fengari.lauxlib
const lualib   = fengari.lualib
const L = lauxlib.luaL_newstate()
lualib.luaL_openlibs(L)
const code = `
print ('LUA: adder inited')
function adder (x)
        print ('LUA: adder called with ' .. x)
        return function (y)
                print ('LUA: curried add called with ' .. y .. '. Curried value is '.. x)
                return x + y
        end

end
`
let ok = lauxlib.luaL_dostring(L, lua.to_luastring(code))
if (ok) return console.log(`Error invoking dostring: ${ok} ${lua.lua_tojsstring(L, -1)}`)

function luaAdder (x) {
        lua.lua_getglobal(L, lua.to_luastring('adder'))
        lua.lua_pushinteger(L, x)
        ok = lua.lua_pcall(L, 1, 1, 0)
        if (ok) return console.log(`Error invoking pcall: ${ok} ${lua.lua_tojsstring(L, -1)}`)
        const closure = // TODO get the returned lua function from the stack?
        return function (y) {
                // TODO execute "closure" with y?
        }
}

const curried14 = luaAdder(14)
const curried3 = luaAdder(3)
console.log(curried14(8)) // Should say 22!
console.log(curried3(7)) // Should say 10!
```

I don't actually know how to get the curried function returned from the lua code and execute it at a later time. I tried to look at the C API docs but I found no help there. Plus, I'm wondering if there's a particular way to do that in fengari. Any insight would be appreciated!

**Comment by RyanSquared** [comment]
Correct me if I'm wrong, but should this not instead be stored in some kind of registry table? I'm not sure if it's possible to "store" a Lua function for later use without one - I'm not sure this is possible in C either.

**Comment by cristiano-belloni** [comment]
@RyanSquared - not sure too (that's why I'm asking :) ), but imho it should be possible, as functions are first-class in Lua and closures are supported.

I *can* execute the curried function directly from the stack (see the example below), but i guess the question is if it can be stored and executed at a later time.

``` javascript
global.WEB = false
const fengari = require('./fengari/src/fengari')
const lua = fengari.lua
const lauxlib = fengari.lauxlib
const lualib   = fengari.lualib
const L = lauxlib.luaL_newstate()
lualib.luaL_openlibs(L)
const code = `
print ('LUA: adder inited')
function adder (x)
  print ('LUA: adder called with ' .. x)
  return function (y)
    print('LUA: curried function called with ' .. y)
    return x + y
  end

end
`
let ok = lauxlib.luaL_dostring(L, lua.to_luastring(code))
if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)

function luaAdder (x) {
  // if the next line is omitted, we die with not enough elements in the stack!
  lua.lua_getglobal(L, lua.to_luastring('adder'))
  lua.lua_pushinteger(L, x)
  ok = lua.lua_pcall(L, 1, 1, 0)
  if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)
  lua.lua_pushinteger(L, 8)
  ok = lua.lua_pcall(L, 1, 1, 0)
  if (ok) return console.log(`Error calling ${lua.lua_tostring(L, -1)}`)
  const sum = lua.lua_tointeger(L, -1)
  lua.lua_pop(L, 1)
  return sum
}

console.log(luaAdder(14))
```

**Comment by giann** [comment]
@cristiano-belloni I think what you need is [lua_toproxy](https://github.com/fengari-lua/fengari#p--lua_toproxyl-idx)

**Comment by daurnimator** [comment]
> I don't actually know how to get the curried function returned from the lua code and execute it at a later time. I tried to look at the C API docs but I found no help there.

The closure is on the stack; you can call it there (e.g. by using `lua_call`).
Or you can store it away somewhere else in the lua state (e.g. in the registry, or set a global, etc).
Or as @giann mentioned, the unique fengari solution is to call `lua_toproxy` to take a reference into a javascript variable.

**Comment by cristiano-belloni** [comment]
@giann @daurnimator Thanks, it works! I'll copy my implementation below for future reference and close this. Thanks for this project, it's brilliant.

```javascript
global.WEB = false
const fengari = require('./fengari/src/fengari')
const lua = fengari.lua
const lauxlib = fengari.lauxlib
const lualib   = fengari.lualib
const L = lauxlib.luaL_newstate()
lualib.luaL_openlibs(L)
const code = `
print ('LUA: adder inited')
function adder (x)
  print ('LUA: adder called with ' .. x)
  return function (y)
    print ('LUA: curried called with ' .. y)
    return x + y
  end
end
`
let ok = lauxlib.luaL_dostring(L, lua.to_luastring(code))
if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)
function luaAdder (x) {
  // if the next line is omitted, we die with not enough elements in the stack!
  lua.lua_getglobal(L, lua.to_luastring('adder'))
  lua.lua_pushinteger(L, x)
  ok = lua.lua_pcall(L, 1, 1, 0)
  if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)
  const curried = lua.lua_toproxy(L, -1)
  return function (y) {
    curried(L)
    lua.lua_pushinteger(L, y)
    ok = lua.lua_pcall(L, 1, 1, 0)
    if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)
    const sum = lua.lua_tointeger(L, -1)
    lua.lua_pop(L, 1)
    return sum
  }
}
const curried14 = luaAdder(14)
const curried3 = luaAdder(3)
console.log(curried14(8)) // It says 22!
console.log(curried3(7)) // It says 10!
```

**Comment by cristiano-belloni** [comment]
> Note that lua <=> JS interop is mostly solved by fengari-interop
It's a bit hard to see how to invoke Lua functions though. I need fengari mainly to experiment with embedding a DSL, so I need JS => Lua interop more than Lua => JS, but I can't see the docs. Opened an issue [here](https://github.com/fengari-lua/fengari-interop/issues/8).
